source "https://rubygems.org"

# Fastlane - automation tool for iOS and Android deployment
# https://docs.fastlane.tools/
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
